Test trigger

diff --git a/.github/workflows/opa-check.yaml b/.github/workflows/opa-check.yaml
--- a/.github/workflows/opa-check.yaml
+++ b/.github/workflows/opa-check.yaml
@@ -36,4 +36,14 @@ jobs:
 
       - name: Run OPA Policy Check
         run: |
-          opa eval --data bucket.rego --input tfplan.json "data.terraform.demo.allow"
+         RESULT=$(opa eval --format raw --data bucket.rego --input tfplan.json "data.terraform.demo.allow")
+         echo "OPA result: $RESULT"
+         if [ "$RESULT" != "true" ]; then
+           echo " OPA policy check failed!"
+           exit 1
+         fi
+         echo " OPA policy check passed!"
+
+      - name: Terraform Apply
+        if: success()   # only runs if OPA passed
+        run: terraform apply -auto-approve tfplan.binary
